root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - tsconfig.app.json
    - tsconfig.spec.json
  sourceType: module
extends:
  - eslint:recommended
  - plugin:node/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@angular-eslint/recommended
plugins:
  - rxjs
  - node
rules:
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
  "@typescript-eslint/ban-ts-comment": warn
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-use-before-define": off
  "@typescript-eslint/no-warning-comments": off
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/no-var-requires": off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/ban-types": off
  "@typescript-eslint/camelcase": off
  "@typescript-eslint/interface-name-prefix": off
  "@typescript-eslint/no-namespace": off
  "@typescript-eslint/no-this-alias": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-inferrable-types": off
  "@typescript-eslint/member-ordering":
    - "error"
    - default:
        memberTypes:
          - "signature"
          - "field"
          - "constructor"
          - "method"
  "@angular-eslint/no-host-metadata-property": off
  node/no-missing-import: off
  node/no-empty-function: off
  node/no-unpublished-import: off
  node/no-extraneous-require: error
  node/no-unpublished-require: error
  node/no-unsupported-features/es-syntax: off
  node/no-missing-require: off
  node/shebang: off
  block-scoped-var: error
  eqeqeq: off
  no-var: error
  prefer-const: error
  prefer-arrow-callback: error
  no-trailing-spaces: error
  quotes: off
  no-restricted-properties:
    - "error"
    - object: describe
      property: only
    - object: it
      property: only
  no-dupe-class-members: off
  require-atomic-updates: off
  no-undef: off
  no-inner-declarations: off
  no-redeclare: off
  eol-last: off
  no-console: off
  no-case-declarations: off
  no-prototype-builtins: off
  no-extra-boolean-cast: error
  no-else-return: error
  prefer-rest-params: error
  rxjs/ban-operators:
    - error
    - first: use take(1) instead
  rxjs/no-ignored-observable: error
  rxjs/no-unbound-methods: error
  rxjs/no-unsafe-takeuntil: error
  rxjs/no-nested-subscribe: error
ignorePatterns:
  - "**/*.js"
