root: true
parser: '@typescript-eslint/parser'
extends:
  #- eslint:recommended
  - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  "no-explicit-any": ["off"]
  "@typescript-eslint/no-explicit-any": ["off"]
  "@typescript-eslint/no-throw-literal": "off"
#  "@typescript-eslint/ban-ts-comment": off
ignorePatterns:
  - "**/*.html"
