version: '3.6'

volumes:
  db-data: {}

networks:
  keycloak-net:
    driver: bridge

services:

#  web:
#    build: ../client_app/
#    ports:
#      - "4201:80"
#    networks:
#      - keycloak-net

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    volumes:
      - ./sample-realm.json:/opt/keycloak/data/import/main-realm.json:ro
    environment:
      KC_LOG_LEVEL: INFO
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: /auth
      KC_FEATURES: docker
      KC_DB: ${DB_VENDOR:-postgres} #h2|postgres|mysql|mariadb|oracle|mssql
      KC_DB_URL_HOST: postgres_svc
      KC_DB_URL_PORT: 5432
      KC_DB_URL: jdbc:postgresql://postgres_svc:5432/postgres
      KC_DB_URL_DATABASE: ${KEYCLOAK_DATABASE_NAME:-postgres}
      KC_DB_SCHEMA: ${DB_SCHEMA:-public}
      KC_DB_USERNAME: ${DB_USER:-postgres}
      KC_DB_PASSWORD: ${DB_PASSWORD:-postgres}
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD:-admin}
    entrypoint: [ '/opt/keycloak/bin/kc.sh', 'start-dev', '--import-realm','--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true' ]
    restart: unless-stopped
    networks:
      - keycloak-net
    ports:
      - "8080:8080"

  postgres_svc:
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - ${DB_DATA_DIR:-db-data}:/data/postgres
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - keycloak-net
